apiVersion: apps/v1
kind: Deployment
metadata:
  name: reviewservice
  labels:
    app: reviewservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reviewservice
  template:
    metadata:
      labels:
        app: reviewservice
    spec:
      containers:
      - image: reviewservice
        imagePullPolicy: Always
        name: reviewservice
        env:
        - name: SPLUNK_OTEL_AGENT
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: OTEL_SERVICE_NAME
          value: 'reviewservice'
        - name: SPLUNK_METRICS_ENDPOINT
          value: "http://$(SPLUNK_OTEL_AGENT):9943"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://$(SPLUNK_OTEL_AGENT):4317"
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: 'deployment.environment=frothly-eks'
        - name: OTEL_PROPAGATORS
          value: 'b3multi'
---
apiVersion: v1
kind: Service
metadata:
  name: reviewservice
spec:
  type: NodePort
  selector:
    app: reviewservice
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30000
